### ISSUE TITLE
Installing msi on Windows

### ISSUE THREAD

**Issue by Paterfiets** [quamplex/geonkick#12]
Hi,

I tried to install Geonkick on Windows using the Geonkickinstaller.msi but I think I am missing something or might be doing something wrong.

I can see in my apps that there is something installed but when I go to my Program files there is only an empty folder and I have no option to open the program somewhere.  Also no Vst shows up in my DAW.

Any ideas ?

Regards 
Pater

**Comment by iurienistor** [comment]
@Paterfiets Hi, there is no program/standalone version of Geonkick that can be opened. The folder C:\Program Files\Geonkick\ should not be empty, it should contain some DLLs, otherwise vst it will not show up. If that folder is really empty. Maybe the antivirus removed them or not allowed to install? Check also the folder Program C:\Program Files\Common Files\VST3\Geonkick.vst3\Contents\x86_64-win to contain a file Geonkick.vst3

**Comment by Paterfiets** [comment]
I found the vst3 file in the directory you mentioned. For some reason Bitwig didnt see it which is strange as I have other plugins with the exact same folder structure. I had to move the geonkick.vst3 file out of the x86_64-win folder and placed it directly into the Geonkick3.vst3 folder and now it showes up in Bitwig.

Thanks for the help !

**Comment by iurienistor** [comment]
@Paterfiets If you have other DAWs, please, report if also they don't see the vst (without moving them out of that folder). Also, please, report if you'll meet the same issues like here: https://github.com/Geonkick-Synthesizer/geonkick/issues/10

**Comment by RobU23** [comment]
Just some quick test feedback on the default VST3 location on Windows (Program Files\Common Files\VST3\Geonkick.vst3\Contents\x86_64-win).  

Geonkick is found and can be loaded by the following hosts : Bitwig 5, Cubase 11, Live 11, Reaper 7 and Reason 12.

Cheers
Rob.U

**Comment by iurienistor** [comment]
@RobU23 thanks for the feedback!
