### ISSUE TITLE
Lv2 Backwards Compatibility

### ISSUE THREAD

**Issue by valambrou** [quamplex/geonkick#19]
With the release of version 3 and onward,  Ardour projects containing the lv2 version of the plugin from 2.10 report that the plugin is missing and fail to load it.  Geonkick plugin ver 3.2.0 is installed and I can add it as a new one to my track but cannot transfer the settings from the disabled one. I assume it has to do with backwards compatibility and wondering if there is any workaround to at least copy/transfer settings from the disabled one.

**Comment by iurienistor** [comment]
@valambrou Hi, you mean Windows version of LV2?

**Comment by valambrou** [comment]
Hello @iurienistor! My bad, forgot to mention, I mean the linux version.

**Comment by iurienistor** [comment]
@valambrou thanks, I'll check

**Comment by iurienistor** [comment]
@valambrou Ah, actually I forgot... if you'll open a project that is using old version Ardour will say that cannot find because starting from version 3.0 the URL name of the LV2 plugin was changed to "geonkick"... before it contained a name that no more has to do with the project. 

You need to open the project with the old version and save kit preset or preset and load back into the new version. Anyway the new version has some changes that for some cases the sounds may be a little different... thus, it is not 100% compatible ... filters were corrected with a small fix in the new version.

Another hack is to get the code of the new version and change the URL name back and recompile. Anyway, I don't recommend to use new version with old projects because is not really compatible.

**Comment by valambrou** [comment]
Ok,thanks @iurienistor! I'll do it that way. Keep up the good work, I'll mark this issue as closed.

**Comment by x42** [comment]
> before it contained a name that no more has to do with the project.

So what? It's just an identifier, users don't even see that.
You can use any random test as long as it's unique (and a valid URI).
URIs identifying the same resource are not supposed to change.

besides, breaking sessions does not really provide a good user experience.

**Comment by iurienistor** [comment]
@x42 While it's merely an identifier, the plugin URI contains, as I mentioned above, unrelated content: http://geontime.com/. This domain is no longer under my control and is currently up for sale. Someone may acquire this domain and publish unrelated material on. The code is also visible to users, and I want it to direct to the right places, like geonkick.org, which is relevant, and not to random domains.
