### ISSUE TITLE
.msi windows installer does nothing

### ISSUE THREAD

**Issue by D4HRK** [quamplex/geonkick#20]
Just downloaded the v3.2.0 msi installer for Windows on the official website, launched it, but nothing happens ... Cursor is in "work" mode, but the installer seems to be traped in an endless  loop or something ...
I'm on Windows 10/64.

**Comment by iurienistor** [comment]
@D4HRK Hi, it might happen that the antivirus is doing something because I've never met this problem... you can download the artifacts from https://github.com/Geonkick-Synthesizer/geonkick/actions/runs/7276731873/artifacts/1126725443 and install the plugin manually. Just copy the folder Geonkick.vst into the corresponding folder of VST3 plugins on your machine.

**Comment by D4HRK** [comment]
Thanks.
My antivirus is just the standard W10 defender, I doubt it's related to AV because I got no message from AV.
Anyway I will check with the artifacts.
