### ISSUE TITLE
The scroll doesn't work correctly for file browser

### ISSUE THREAD

**Issue by iurienistor** [quamplex/geonkick#33]
The scroll doesn't work correctly for file browser. Issue: https://github.com/Geonkick-Synthesizer/geonkick/issues/26

**Comment by o-bardiuk** [comment]
![geonkick](https://github.com/Geonkick-Synthesizer/geonkick/assets/139021881/df13f3c9-1c55-4116-9107-03ac9c73daef)

There is something wrong with the scroll bar.

Also if I want to save a preset, I think it should take me to the user presets folder of Geonkick (maybe in the user/Documents folder) or give a way to create a folder, or paste a path. Finding a path manually takes a lot of time. By default, the Explorer takes you to the User folder but I don't save presets there and I scroll a lot when looking for a preferred folder in the list. Also, folders are sorted so that Capitalized letters are before lowercase. So my folder is at the bottom of the list.

In general, I like the approach of popular synth-makers (Serum, Vital), they create the factory folder, and inside there is a User folder, where users save their presets.

**Comment by iurienistor** [comment]
Some parts are related to https://github.com/Geonkick-Synthesizer/geonkick/issues/5 I'll make some fixes and implementations to create the folder and bookmarks the folder.

**Comment by iurienistor** [comment]
@o-bardiuk  Form your screenshot the scrollbar is ok. and the scrolling seems to work ok too. The scroollbar is not a standard one (is not like a slider). Maybe later I'll implement a more standard scrollbar.

**Comment by iurienistor** [comment]
@o-bardiuk I'llmark this as duplicate of #5

**Comment by o-bardiuk** [comment]
> The scroollbar is not a standard one (is not like a slider).

Oh, I see, but then I can not point and click it and scroll to the very bottom. If I try to click it - the window disappears. So instead I do a lot of mouse wheel scrolls to get to the very bottom of the list.

**Comment by iurienistor** [comment]
@o-bardiuk " If I try to click it - the window disappear"... yes, this is a bug. Need to be fixed... but will be fixed, when I'll update all the browser.
