### ISSUE TITLE
CPU max out with 3.3.0 and 3.3.1 in FL Win10

### ISSUE THREAD

**Issue by MaZe6K** [quamplex/geonkick#38]
Version 3.3.0 and 3.3.1 cause massive CPU usage in my FL Studio on Win 10 (70-100%)

With version 3.2.0 it always was at 1-2% CPU.

**Comment by iurienistor** [comment]
I have this

![perf](https://github.com/Geonkick-Synthesizer/geonkick/assets/56111777/db6a96ec-f904-42c6-b8de-2899f787f629)

**Comment by MaZe6K** [comment]
weird... here it looks like this

![geonkick331highcpu](https://github.com/Geonkick-Synthesizer/geonkick/assets/50169405/66fc9ab1-5c38-434e-a7fb-115eac84797a)

with the default startup sound... with some kits it got as low as 25%, but still far too much, 3.2.0 just stays at 1-2% always here, too.

**Comment by iurienistor** [comment]
@MaZe6K Could you try with other hosts if the load will be the same?

**Comment by MaZe6K** [comment]
just checked in bespoke synth... there it shows a constant 35%

and in VCV Rack in the VCV Host module in otherwise empty patch 24%

In FL it fluctuates between 25 and 72%.. I guess they all measure differently? definitely far too high everywhere.

**Comment by iurienistor** [comment]
@MaZe6K Ok, I've found the problem, but I'll create a commit later this week.

**Comment by iurienistor** [comment]
@MaZe6K I created a commit https://github.com/Geonkick-Synthesizer/geonkick/commit/3035dd5ed57ec334398052a1b55ee110daba8f39 and in the actions the installer for this commit will be created. You can install and see if the problem is fixed. I could reproduce the problem with Ardour, Reaper and other hosts and now I fixed with this commit.
