### ISSUE TITLE
midi input channels

### ISSUE THREAD

**Issue by sjomae** [quamplex/geonkick#40]
Am I correct that it's currently not possible to set a input midi channel? 

If so, that will make it a feature request.

**Comment by iurienistor** [comment]
@sjomae Geonkick has one input MIDI channel for playing the keys

**Comment by sjomae** [comment]
Geonkick just listens to all midi channels right? So if you connect a midi device to both Surge synth and Geonkick, you can't set a specific midi channel for Geonkick. So if the notes of both synths overlaps, both will play (which is not what you want). A user should be able to set Surge to midi channel 1 and Geonkick to midi channel 2 (as example).

**Comment by iurienistor** [comment]
@sjomae Yes, it listens to all channels, and you are right; is not good. Actually never had to think about MIDI input since the first time it was implemented. So, there should be a way set the input MIDI channel. 

Now I want also to ask if maybe even to be able to set a separate MIDI channel for every instrument from the kit?... Because if the button "tune" (see the top bar of Geonkick GUI) is enabled for an instrument, than the instrument will be pitch shifted in the range of an 1 octave depending on the key pressed, i.e. it will play notes in the range of an octave (but in monophonic way).

**Comment by sjomae** [comment]
> Now I want also to ask if maybe even to be able to set a separate MIDI channel for every instrument from the kit?.

Then it would be able to play two geonkick instruments with the same keyboard key right? I'm not a keyboard drummer, so I'm not sure how useful that is. If it makes it not much more complex to implement midi input channels and it can easily be displayed in the GUI, I would say, why not?
