### ISSUE TITLE
Geonkick can't work as expected in Studio One 5

### ISSUE THREAD

**Issue by Watermelon617** [quamplex/geonkick#77]
I use Studio One 5 in Windows 10. 
Install Geonkick vst3 plugin.

When load Geonkick on the track, open the GUI, it will continously pop up "the plugin isn't working as expected" and ask me to restart Studio One. But nothing changed. And the plugin only makes short beep sound every time when press a note and release a note. Even I load the preset, it also can not help.

**Comment by iurienistor** [comment]
Hi, I'll try to reproduce If I'll be able to get a free/trial version of Studio One 5 host. It makes a beep because the DSP part of the plugin works ok, plays the default sound.

**Comment by iurienistor** [comment]
Here is Windows 11 with the latest Studio One 6. It works. It might be that because Geonkick uses the most recent changes in the VST3 SDK, it may not be fully compatible with Studio One 5.

I cannot get a trial version of Studio One 5, so, I won't be able to reproduce this issue.

![Screeshort](https://github.com/user-attachments/assets/e64a5aa3-5651-4862-b072-43c22bb7931e)
